# Generated by Django 6.1 on 2026-08-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(help_text="e.g. '1.0', '2026-08-26'. Shown to the app so it can detect changes.", max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full document body. Markdown is fine if your app renders it; plain text also works.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active document per doc_type should exist at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='legal.legaldocument')),
            ],
        ),
    ]
