# Generated by Django 5.2.9 on 2026-09-04 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video Recording'), ('PDF', 'PDF'), ('ARTICLE', 'Article'), ('EXTERNAL_LINK', 'External Link'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('LIVE_CLASS', 'Live Class')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text="For VIDEO items — used to show '45:20' style durations in the app.", null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text="For PDF/file items — used to show '2.4 MB' style sizes in the app.", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('current_lesson_title', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the course (Module 1, 2, 3...).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lecture number within the module (Lecture 1, 2, 3...).')),
                ('published_at', models.DateField(blank=True, help_text="Date shown in the app, e.g. '12 May 2025'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('badge_text', models.CharField(blank=True, default='SPECIAL OFFER', max_length=50)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('target_type', models.CharField(choices=[('course', 'Course'), ('category', 'Category'), ('quiz', 'Learning Path Quiz'), ('external', 'External Link'), ('custom', 'Custom Action')], default='course', max_length=30)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_url', models.URLField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(default='Claim Offer', max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(default='Learning Strategy', max_length=100)),
                ('author_name', models.CharField(default='Baoiam Mentor', max_length=150)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_name', models.CharField(blank=True, default='lightbulb', max_length=50)),
                ('publish_date', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tip of the Day',
                'verbose_name_plural': 'Tips of the Day',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_name', models.CharField(blank=True, default='star', max_length=50)),
                ('highlight_stat', models.CharField(blank=True, help_text="e.g. '98% Success Rate'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_code', models.CharField(blank=True, help_text="Short badge text shown in the app, e.g. 'UI/UX', 'WD', 'DA', 'PM'.", max_length=10)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instructor_name', models.CharField(blank=True, default='Baoiam Instructor', max_length=150)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('lessons_count', models.PositiveIntegerField(default=12)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
