# Generated by Django 5.2.9 on 2026-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Empowering learners worldwide', max_length=255)),
                ('mission_text', models.TextField(default='To democratize education by providing accessible, high-quality learning experiences that empower learners worldwide to achieve their full potential.')),
                ('vision_text', models.TextField(blank=True, default='')),
                ('trusted_by_labels', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Overview',
                'verbose_name_plural': 'About Us Overview',
            },
        ),
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 1M+, 5000+, 98%, 150+', max_length=50)),
                ('label', models.CharField(help_text='e.g. Students, Courses, Success Rate, Countries', max_length=100)),
                ('icon', models.CharField(default='Groups', help_text='Material Icon name e.g. Groups, MenuBook, Star, Public', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Stat',
                'verbose_name_plural': 'Impact Stats',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. UNIV Business School, Web Developer', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('story', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Approval status (visible if true)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. CEO & Founder, Head of Education', max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='School', help_text='Material Icon name e.g. School, VideoCall, SupportAgent, PhoneAndroid, WorkspacePremium, TrendingUp', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us / Offer Item',
                'verbose_name_plural': 'Why Choose Us / Offer Items',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
